### PR TITLE
Change local dev ports for db, editor, and app

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues

* https://github.com/cityofaustin/atd-data-tech/issues/20340

* VZE (`/editor`): `3000` => `3002`
* VZE (`/app`): `3000` => `3002`
* DB: `5432` => `5431`

## Testing

Start your local VZ: DB, editor, and app

---

#### Ship list

- [ ] Check migrations for any conflicts with latest migrations in `main` branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Review by mddilley — COMMENTED** [review]
Awesome - I tested this with the Moped stack already spun up, and all VZ services started up. 🚀 Such an upgrade. 🙌

I saw the NearMap tiles are not loading locally, and I also saw the app readme needs the port updated in the "Quick Start" section. Good news is that I'm caught up to all the awesome changes in this app that I haven't reviewed yet. Looks amazing!

**Review by frankhereford — APPROVED** [review]
Yes, Yes, Yes, a thousand times yes - thank you John!!!

**Review by chiaberry — APPROVED** [review]
I am running both moped and vz locally *at the same time*! banner day

**Comment by johnclary** [comment]
OK, I updated the special `hasura console` port to be `9696` and fixed the outdated reference to `3000` in the. `/app` readme.

**Comment by johnclary** [comment]
Thanks @mddilley for pointing out the nearmap tiles issue—I will reach open a servicedesk ticket to get the allow list updated on our API key 🙏

**Comment by johnclary** [comment]
Thomas @ CTM GIS updated our Nearmap API key whitelist—we have imagery on `localhost:3002` 🎉

**Pull request merged**
